import http from 'http'; import fs from 'fs'; import path from 'path';
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const { chromium } = require('playwright-core');
const ROOT='D:/VSCode projects/DUSK_v2.0';
const CHROME='C:/Program Files/Google/Chrome/Application/chrome.exe';
const OUT='C:/Users/serge/AppData/Local/Temp/claude/D--VSCode-projects-DUSK-v2-0/0a1e223e-b6d1-498e-a433-745713f8b509/scratchpad';
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.jpg':'image/jpeg'};
const srv=http.createServer((q,s)=>{let u=decodeURIComponent(q.url.split('?')[0]);if(u==='/')u='/index.html';
  fs.readFile(path.join(ROOT,u),(e,d)=>{if(e){s.writeHead(404);s.end('nf');return;}s.writeHead(200,{'Content-Type':MIME[path.extname(u)]||'application/octet-stream'});s.end(d);});});
(async()=>{
  await new Promise(r=>srv.listen(0,r));
  const port=srv.address().port; const base=`http://localhost:${port}`;
  const browser=await chromium.launch({executablePath:CHROME,headless:true});
  const page=await (await browser.newContext({viewport:{width:1200,height:900}})).newPage();
  await page.goto(`${base}/index.html`); await page.waitForTimeout(800);
  await page.evaluate(()=>{ for(let i=0;i<3;i++) state.tasks.push({id:state.nextId++,uid:'X'+i,createdAt:nowTs(),updatedAt:nowTs(),text:'Задача '+(i+1),checked:false,priority:'none',groupId:null,deadline:null,note:'',noteOpen:false,order:i,repeat:'none',cycleChecked:false,nextReset:null,subtasks:[],subtasksOpen:false}); saveState(); render();
    document.getElementById('sync-glyph-btn').setAttribute('data-sync','ok'); });
  await page.waitForTimeout(300);
  const eye=await page.locator('#sync-glyph-btn').boundingBox();
  await page.locator('#sync-glyph-btn').click();
  await page.waitForTimeout(300);
  const panel=await page.evaluate(()=>{ const p=document.querySelector('.snooze-menu.sync-panel'); if(!p) return null; const r=p.getBoundingClientRect(); return {top:r.top,bottom:r.bottom,left:r.left,right:r.right,h:r.height}; });
  console.log('eye', JSON.stringify(eye));
  console.log('panel', JSON.stringify(panel));
  console.log('opensAbove', panel ? panel.bottom <= eye.y + 2 : 'NO PANEL');
  console.log('onScreen', panel ? (panel.top>=0 && panel.bottom<=900 && panel.left>=0 && panel.right<=1200) : 'NO PANEL');
  await page.screenshot({path:OUT+'/eye_panel_full.png'});
  await browser.close(); srv.close();
})().catch(e=>{console.error('CRASH',e);process.exit(2);});
