import { serve, launch, openApp } from './lib.mjs';
import { richSeed } from './seed.mjs';
const { srv, port } = await serve();
const browser = await launch();
const { ctx, page: p } = await openApp(browser, { device: 'pixel7', seed: richSeed(), port });
const isOpen = () => p.evaluate(() => getComputedStyle(document.getElementById('deadline-modal')).display !== 'none');
await p.evaluate(() => globalThis.openDeadlineModal(12));
await p.waitForTimeout(450);
console.log('opened:', await isOpen());
await p.evaluate(() => { const b = document.querySelector('#deadline-modal [data-mode="date"], .dl-mode-btn[data-mode="date"]'); console.log; if (b) b.click(); });
await p.waitForTimeout(300);
console.log('after mode click:', await isOpen());
await p.evaluate(() => segInputs['dl-date']._focus(0));
await p.keyboard.type('2512');
await p.waitForTimeout(200);
console.log('after typing:', await isOpen(), await p.evaluate(() => segInputs['dl-date'].segs.map(s=>s.buf).join('|')));
await p.setViewportSize({ width: 915, height: 412 });
await p.waitForTimeout(600);
console.log('after rotate:', await isOpen(), await p.evaluate(() => segInputs['dl-date'].segs.map(s=>s.buf).join('|')));
await browser.close(); srv.close();
